import { Timestamp, DocumentData, FirestoreDataConverter, QueryDocumentSnapshot } from "firebase/firestore";

/**
 * ARCHITECTURE NOTE:
 * We split data into 'providers' (static/profile) and 'provider_status' (dynamic/live)
 * to avoid hotspotting a single document with frequent writes (GPS/Online status).
 */

export interface ProviderProfile {
    id: string; // Auth UID

    // Identity
    displayName: string;
    profession: string;   // Główna specjalizacja
    avatarUrl: string;

    // Search Optimization (Map Pattern)
    // replaces array-contains for multiple categories
    // e.g. { "hydraulik": true, "awaria24h": true }
    services: { [key: string]: boolean };

    // Keywords for prefix search (Generated by cloud function or client)
    // ["w", "wa", "war", "warsz", "warszawa", "hydr", "hydraulik"]
    searchTerms?: string[];

    // Economic
    basePrice: number;
    currency: string;

    // Metrics
    rating: number;        // Avg rating
    reviewsCount: number;
    completedOrders: number;

    // Operating Base (Approximate location for listing)
    // NOT the live location. This is static.
    city: string;
    baseLocation: {
        lat: number;
        lng: number;
        geohash: string; // Precision 5 or 6 roughly
    };

    // Metadata
    createdAt: string; // ISO
    updatedAt: string; // ISO
}

export interface ProviderStatus {
    providerId: string; // Link to ProviderProfile

    // State
    isOnline: boolean;
    isBusy: boolean; // In transaction?

    // Telemetry (High frequency updates)
    currentLocation: {
        lat: number;
        lng: number;
        geohash: string; // Precision 10+ for pinpoint
    };

    lastSeen: Timestamp;
}

// Converters for Type-Safety SDK usage

export const providerProfileConverter: FirestoreDataConverter<ProviderProfile> = {
    toFirestore(pro: ProviderProfile): DocumentData {
        return { ...pro };
    },
    fromFirestore(snapshot: QueryDocumentSnapshot): ProviderProfile {
        const data = snapshot.data();
        return data as ProviderProfile;
    }
};

export const providerStatusConverter: FirestoreDataConverter<ProviderStatus> = {
    toFirestore(status: ProviderStatus): DocumentData {
        return { ...status };
    },
    fromFirestore(snapshot: QueryDocumentSnapshot): ProviderStatus {
        const data = snapshot.data();
        return data as ProviderStatus;
    }
};
